/** Declaration file generated by dts-gen */
// declare module "lamejs/lame.all" {
//     class Mp3Encoder {
//         constructor(channels: number, sampleRate: number, kbps: number);
    
//         encodeBuffer(left: Float32Array, right: Float32Array): Int8Array[];
    
//         flush(): Int8Array;
    
//         close(): void;
//     }
//     class WavHeader {
//         numChannels: number;
//         sampleRate: number;
//         bitDepth: number;
//         bytesPerSample: number;
//         blockAlign: number;
//         constructor(numChannels: number, sampleRate: number, bitDepth: number);
//         toBuffer(): ArrayBuffer;
//     }
//     export { Mp3Encoder, WavHeader };
// }

declare module 'lamejs' {
    export class Mp3Encoder {
      constructor(channels: number, sampleRate: number, kbps: number);
      encodeBuffer(left: Int16Array, right?: Int16Array): Int8Array;
      flush(): Int8Array;
    }
  
    export class WavHeader {
      constructor(sampleRate: number, numChannels: number, bytesPerSample: number);
      toBuffer(): ArrayBuffer;
    }
  }